#!/usr/bin/env python3
import configparser

ini_filename = 'scg10ea.ini'
yaml_filename = 'scg10ea-waypoints.yaml'

# Read the INI file
config = configparser.ConfigParser()
config.read(ini_filename)

# Open the output file
with open(yaml_filename, 'w') as yaml_file:

    for key in config['Waypoints']:
        val = int(config['Waypoints'][key])
        if val < 0:
            continue
        row = val // 64
        col = val % 64
        yaml_file.write(
            f"waypoint{key}: waypoint\n"
            f"  Location: {col},{row}\n"
            f"  Owner: Neutral\n")

    yaml_file.write("\n")
    
    ctid = 1
    for key in config['CellTriggers']:
        val = config['CellTriggers'][key]
        cell = int(key)
        row = cell // 64
        col = cell % 64
        yaml_file.write(
            f"CellTrigger{ctid}: waypoint\n"
            f"  Trigger: {val}\n"
            f"  Location: {col},{row}\n"
            f"  Owner: Neutral\n")
        ctid += 1

